inGame 코드 업데이트
ekgns33/SimpleJavaGame pull request #29
Opened 2024-12-04 05:20 UTC by namkyeongsik

## 🐣Title

inGame 코드 업데이트

<br/>

## 🐣Part

---

<br/>

## 🐣Key Changes

- 타이머 업데이트
- 최신 코드 기반 상호작용 업데이트
- 메시지, 대기실 관련 메소드 매개변수 수정

<br/>

## 🐣Simulation

---

<br/>

## 🐣To Reviewer

---

<br/>

## 🐣Next

---

 <br/>

## 🐣Issue

---

<br/>

2024-12-04 07:25 UTC, ekgns33 requested changes
고생하셨어여!

2024-12-04 07:25 UTC, ekgns33 commented on server/src/main/java/org/kunp/Servlet/game/GameContext.java
> +    new Thread(() -> {
스레드를 생성하여 시간을 측정하는 것보다는 시작할때 시간을 저장해놓고 루프에서 비교하는게 좋을 것 같습니다.

```
...
startTime = LocalDateTime.now();
...

if(LocalDateTime.now().minus(starTime) > gameTime
```
이런식으로 하는건 어떨까요

2024-12-04 07:25 UTC, ekgns33 commented on server/src/main/java/org/kunp/Servlet/game/GameContext.java
> +      sendMessage(participants.get(id), "You are in jail and cannot interact!\n");
감옥에 갇힌경우는 아무런 메세지를 안보내주고 무시해도 될것같습니다

2024-12-04 07:25 UTC, ekgns33 commented on server/src/main/java/org/kunp/Servlet/game/GameContext.java
> +        sendMessage(participants.get(targetId), "You have been freed from jail!\n");
문자열 보내는게 있나요

2024-12-04 07:25 UTC, ekgns33 commented on server/src/main/java/org/kunp/Servlet/game/GameContextRegistry.java
> +  public int createGameContext(String roomName, String hostId, int userlimit, int timelimit) {
고쳐주셨군요 감사합니당.
변수명은 카멜케이스로 해주세용~
`userLimit, timeLimit`

2024-12-06 10:11 UTC, namkyeongsik commented on server/src/main/java/org/kunp/Servlet/game/GameContext.java
> +      sendMessage(participants.get(id), "You are in jail and cannot interact!\n");
넵. 코드 지우겠습니다.

2024-12-06 10:13 UTC, namkyeongsik commented on server/src/main/java/org/kunp/Servlet/game/GameContext.java
> +        sendMessage(participants.get(targetId), "You have been freed from jail!\n");
이 부분도 sendMessage 지웠습니다.

2024-12-06 10:16 UTC, namkyeongsik commented on server/src/main/java/org/kunp/Servlet/game/GameContext.java
> +    new Thread(() -> {
GameContext 단일 스레드에서 루프를 통해 비교하면 루프 돌고있는 동안 블로킹되지 않나요? 혹시 가능한 방법이 있을까요?

2024-12-06 18:23 UTC, merged